version: 2

sources:
  - name: thelook_ecommerce
    database: bigquery-public-data
    tables:
      - name: products

models:
  - name: products
    columns:
      - name: id
        tests:
          - dbt_utils.not_constant
          - dbt_utils.at_least_one:
              group_by_columns: ['category']